services:
  dance-school-ui:
    build: .
    container_name: dance-school-ui
    networks:
      - proxy-net
      - dance-school-net
    restart: unless-stopped

networks:
  proxy-net:
    name: proxy-net
    external: true
  dance-school-net:
    name: dance-school-net
    external: true
