services:
  tanzschule-ui:
    build: .
    container_name: tanzschule-ui
    networks:
      - proxy-net
      - tanzschule-net
    restart: unless-stopped

networks:
  proxy-net:
    name: proxy-net
    external: true
  tanzschule-net:
    name: tanzschule-net
    external: true
